### ISSUE TITLE
Remove Alby's Guide

### ISSUE THREAD

**Issue by MerryOscar** [v4v-info/v4v-info.github.io#4]
Ably has completely ripped off Fountain's Podcaster Guide - https://fountain.fm/podcaster-guide

Fountain's Podcaster Guide published 18th August - https://twitter.com/fountain_app/status/1560362445805436930

Alby's guide with the EXACT same format, content, and case studies, even WORD FOR WORD copy - https://guides.getalby.com/podcaster-guide/10.-be-creative-and-experiment

More details on the copy job here - https://fountainfm.notion.site/Alby-ca7557c8fce240e0b46a3bd0ba570c6d

This is really messed up as we spent a lot of time and effort on this guide. I wouldn't have expected this kind of behaviour from another company in the Bitcoin space...

As Alby's is published on GitBook I challenge them to make it open source so we can see the dates they wrote it.

@dergigi can you please remove Alby's from this site.

**Comment by dergigi** [comment]
It is indeed a word-for-word copy. Will remove it, and will consider re-adding it once that is addressed and the guide is more than just a copy of your work.
