### ISSUE TITLE
This site is about Bitcoin and the Fountain network, not about v4v

### ISSUE THREAD

**Issue by grebulon** [v4v-info/v4v-info.github.io#59]
I'm looking for a concise article (or youtube talk) about v4v to attract podcasters to the model. If I give a link to the site to a normal mainstream older guy who asks for "donations" on patreon, he will just get lost clicking around the site.
Also, the site focuses on Bitcoin and the fountain network which is unattractive and not practical for most mainstream podcasters.
What I this is needed:
1. Short description of v4v components written as a short article. The "pieces" page has it all, but it's written like a portal and requires jumping around.
2. Monetization Model - various ways to get paid (paypal, checks, bank transfers), where bitcoin is only one of the options.
3. Discuss (in short) the damage of ads.
4. How to solicit contributions (of all sorts)
All this in a form of an article or a short talk.

**Comment by dergigi** [comment]
Thanks for the feedback!

I would like to encourage you to write what you need and we can integrate it, or in the best case, you open a PR for the changes you want to see.

**Comment by dergigi** [comment]
No further input or pull-request. Closing issue.
